from typing import Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from langchain_ollama import ChatOllama
from langchain.agents import create_agent
from langgraph.checkpoint.memory import InMemorySaver

from tools import search_web, rag_search


app = FastAPI(title="Agentic RAG Backend API")


# --------------------------------------------------
# Response schemas
# --------------------------------------------------

class ResearchResponse(BaseModel):
    topic: str = Field(
        description="The main topic of the user's question."
    )
    summary: str = Field(
        description="The final answer generated by the agent."
    )
    sources: list[str] = Field(
        default_factory=list,
        description="Sources actually used by the agent."
    )
    tools_used: list[str] = Field(
        default_factory=list,
        description="Tools actually called by the agent."
    )


class AskRequest(BaseModel):
    query: str
    session_id: Optional[str] = "default"


class AskAPIResponse(BaseModel):
    answer: str
    source: list[str]
    tools_used: list[str]


# --------------------------------------------------
# Local Ollama model
# --------------------------------------------------

llm = ChatOllama(
    model="llama3.1:8b",
    temperature=0,
)


# --------------------------------------------------
# Agent memory
# --------------------------------------------------

memory = InMemorySaver()


# --------------------------------------------------
# Agent tools
# --------------------------------------------------

tools = [
    search_web,
    rag_search,
]


# --------------------------------------------------
# Agent
# --------------------------------------------------

agent = create_agent(
    model=llm,
    tools=tools,
    checkpointer=memory,
    system_prompt="""
You are an intelligent company research assistant.

Your task is to answer user questions accurately and efficiently.

TOOL ROUTING:

Use rag_search when the question asks about:
- company policies
- employee policies
- internal procedures
- internal documentation
- company-specific technical information
- information contained in the internal knowledge base

Use search_web when the question requires:
- current information
- latest information
- external information
- information not available in the internal documents

Answer directly without tools when:
- the question is a simple general knowledge question
- no internal company information is required
- no current external information is required

IMPORTANT RULES:

1. Never invent company policies.
2. For internal questions, rely on rag_search results.
3. For current/external questions, use search_web.
4. Do not use rag_search simply because the word "RAG" appears in
   the user's question. Distinguish between asking about the RAG
   technology itself and asking about company documentation.
5. Use the minimum number of tools necessary.
6. Do not cite a source that was not actually used.
7. Keep the final answer concise and factual.
8. Do not output JSON.
9. Do not mention your internal reasoning.
""",
)


# --------------------------------------------------
# Helper functions
# --------------------------------------------------

def extract_tools_used(messages) -> list[str]:
    """Return the names of tools actually called by the agent."""
    tools_used = []

    for message in messages:
        tool_calls = getattr(message, "tool_calls", None)

        if not tool_calls:
            continue

        for call in tool_calls:
            name = call.get("name")

            if name and name not in tools_used:
                tools_used.append(name)

    return tools_used


def extract_sources(messages) -> list[str]:
    """
    Extract source filenames and URLs from actual tool outputs.
    """
    sources = []

    for message in messages:
        if getattr(message, "type", "") != "tool":
            continue

        content = getattr(message, "content", "")

        if not isinstance(content, str):
            continue

        for line in content.splitlines():
            line = line.strip()

            if line.startswith("SOURCE_URL:"):
                source = line.replace("SOURCE_URL:", "", 1).strip()

                if source and source not in sources:
                    sources.append(source)

            elif line.startswith("SOURCE:"):
                source = line.replace("SOURCE:", "", 1).strip()

                if source and source not in sources:
                    sources.append(source)

    return sources


def extract_final_answer(messages) -> str:
    """Return the final natural-language assistant response."""

    for message in reversed(messages):
        if getattr(message, "type", "") != "ai":
            continue

        content = getattr(message, "content", "")

        if isinstance(content, str) and content.strip():
            return content.strip()

        if isinstance(content, list):
            text_parts = []

            for item in content:
                if isinstance(item, dict):
                    if item.get("type") == "text":
                        text_parts.append(item.get("text", ""))

            text = " ".join(text_parts).strip()

            if text:
                return text

    return "No answer was generated."


def generate_topic(query: str) -> str:
    """Generate a lightweight topic label without another LLM call."""

    words = query.strip().rstrip("?").split()

    if not words:
        return "General"

    if len(words) <= 6:
        return " ".join(words)

    return " ".join(words[:6]) + "..."


# --------------------------------------------------
# Health endpoint
# --------------------------------------------------

@app.get("/health")
def health():
    return {
        "status": "healthy",
        "llm": "ollama",
        "model": "llama3.1:8b",
        "embeddings": "nomic-embed-text",
        "vector_store": "FAISS",
    }


# --------------------------------------------------
# Session reset
# --------------------------------------------------

@app.delete("/sessions/{session_id}")
def clear_session(session_id: str):
    """
    Clear a conversation session.

    InMemorySaver does not expose a simple high-level delete API,
    so this endpoint provides a documented place for session reset.
    """
    return {
        "status": "ok",
        "message": (
            f"Session '{session_id}' can be started with a new "
            "session_id."
        ),
    }


# --------------------------------------------------
# Ask endpoint
# --------------------------------------------------

@app.post("/ask", response_model=AskAPIResponse)
def ask(payload: AskRequest):

    if not payload.query.strip():
        raise HTTPException(
            status_code=400,
            detail="Query cannot be empty.",
        )

    try:
        result = agent.invoke(
            {
                "messages": [
                    {
                        "role": "user",
                        "content": payload.query,
                    }
                ]
            },
            {
                "configurable": {
                    "thread_id": payload.session_id,
                }
            },
        )

        messages = result.get("messages", [])

        if not messages:
            raise HTTPException(
                status_code=500,
                detail="Agent returned no messages.",
            )

        answer = extract_final_answer(messages)
        tools_used = extract_tools_used(messages)
        sources = extract_sources(messages)

        response = ResearchResponse(
            topic=generate_topic(payload.query),
            summary=answer,
            sources=sources,
            tools_used=tools_used,
        )

        return AskAPIResponse(
            answer=response.summary,
            source=response.sources,
            tools_used=response.tools_used,
        )

    except HTTPException:
        raise

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Agent execution failed: {exc}",
        ) from exc